name: Viewer - Test
on:
  push:
    paths:
      - ".github/workflows/viewer-test.yml"
      - "viewer/**"
    branches:
      - master
  pull_request:
    paths:
      - ".github/workflows/viewer-test.yml"
      - "viewer/**"

defaults:
  run:
    working-directory: viewer

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.17.1
      - run: pnpm install
      - run: yarn test
      - run: yarn build
